# Generated by Django 5.1 on 2024-09-14 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_follow_follower_alter_follow_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likeUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
