# Generated by Django 5.1 on 2024-09-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_like_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
