# Generated by Django 5.1 on 2024-09-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budjet',
            name='amount',
        ),
        migrations.AddField(
            model_name='budjet',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budjet',
            name='outcome',
            field=models.IntegerField(default=0),
        ),
    ]
