# Generated by Django 5.1 on 2024-10-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_transaction_delete_budjet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
