# Generated by Django 5.1 on 2024-10-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
